CC = gcc
CFLAGS = -Wall -Wextra -Wconversion -std=c11
DEPS = 

all: test0 test1 test2 test3 test4 test5 test6 test7 test8 test9 test10 test11

test0: test0.o
	$(CC) -o TEST0 test0.o ../OSMP.o ../keys.o
test0.o: test0.c $(DEPS)
	$(CC) $(CFLAGS) -m64 -g -c -o $@ $<

test1: test1.o
	$(CC) -o TEST1 test1.o ../OSMP.o ../keys.o
test1.o: test1.c $(DEPS)
	$(CC) $(CFLAGS) -m64 -g -c -o $@ $<

test2: test2.o
	$(CC) -o TEST2 test2.o ../OSMP.o ../keys.o
test2.o: test2.c $(DEPS)
	$(CC) $(CFLAGS) -m64 -g -c -o $@ $<

test3: test3.o
	$(CC) -o TEST3 test3.o ../OSMP.o ../keys.o
test3.o: test3.c $(DEPS)
	$(CC) $(CFLAGS) -m64 -g -c -o $@ $<

test4: test4.o
	$(CC) -o TEST4 test4.o ../OSMP.o ../keys.o
test4.o: test4.c $(DEPS)
	$(CC) $(CFLAGS) -m64 -g -c -o $@ $<

test5: test5.o
	$(CC) -o TEST5 test5.o ../OSMP.o ../keys.o
test5.o: test5.c $(DEPS)
	$(CC) $(CFLAGS) -m64 -g -c -o $@ $<

test6: test6.o
	$(CC) -o TEST6 test6.o ../OSMP.o ../keys.o
test6.o: test6.c $(DEPS)
	$(CC) $(CFLAGS) -m64 -g -c -o $@ $<

test7: test7.o
	$(CC) -o TEST7 test7.o ../OSMP.o ../keys.o
test7.o: test7.c $(DEPS)
	$(CC) $(CFLAGS) -m64 -g -c -o $@ $<

test8: test8.o
	$(CC) -o TEST8 test8.o ../OSMP.o ../keys.o
test8.o: test8.c $(DEPS)
	$(CC) $(CFLAGS) -m64 -g -c -o $@ $<

test9: test9.o
	$(CC) -o TEST9 test9.o ../OSMP.o ../keys.o
test9.o: test9.c $(DEPS)
	$(CC) $(CFLAGS) -m64 -g -c -o $@ $<

test10: test10.o
	$(CC) -o TEST10 test10.o ../OSMP.o ../keys.o
test10.o: test10.c $(DEPS)
	$(CC) $(CFLAGS) -m64 -g -c -o $@ $<

test11: test11.o
	$(CC) -o TEST11 test11.o ../OSMP.o ../keys.o
test11.o: test11.c $(DEPS)
	$(CC) $(CFLAGS) -m64 -g -c -o $@ $<
